name: Autorelease

on:
  push:
    branches:
      - "master"

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        repository: 'davidgiven/comal65'
        path: 'comal65'
    - uses: actions/checkout@v3
      with:
        repository: 'davidgiven/llvm-mos-sdk'
        path: 'llvm-mos-sdk'
    - name: get llvm-mos-sdk version
      run: echo "MOS_SDK_VERSION=$(cd llvm-mos-sdk && git rev-parse --short HEAD)" >> $GITHUB_ENV

    - name: apt
      run: sudo apt update && sudo apt install libfmt-dev libelf-dev

    - name: cache llvm-mos
      id: cache-llvm-mos
      uses: actions/cache@v3
      env:
        cache-name: cache-llvm-mos
      with:
        path: ~/llvm-mos
        key: ${{ runner.os }}-build-${{ env.cache-name }}-ver-${{ env.MOS_SDK_VERSION }}

    - if: ${{ steps.cache-llvm-mos.outputs.cache-hit != 'true' }}
      name: install llvm-mos
      run: |
        mkdir -p llvm-mos-sdk/build
        (cd llvm-mos-sdk/build && cmake -G "Make" -DCMAKE_INSTALL_PREFIX=$HOME/llvm-mos ..)
        (cd llvm-mos-sdk/build && make install)

    - name: make
      run: PATH=$PATH:$HOME/llvm-mos/bin make -C comal65 LLVM=

    - name: date
      run: |
        echo "RELEASE_DATE=$(date --rfc-3339=date)" >> ${GITHUB_ENV}

    - name: tag
      run: |
        cd comal65
        git config user.name "davidgiven"
        git config user.email "dg@cowlark.com"
        git tag -f dev
        git push -f origin dev
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: delete-old-assets
      uses: mknejp/delete-release-assets@v1
      with:
        token: ${{ github.token }}
        tag: dev
        assets: | 
          bbctube.ssd
        fail-if-no-assets: false

    - name: release
      uses: softprops/action-gh-release@v1
      with:
        name: Development build ${{ env.RELEASE_DATE }}
        files: |
          bin/bbctube.ssd
        tag_name: dev
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

